In [1]:
import pandas as pd

In [ ]:
df = pd.read_feather("/dsi/efroni-lab/sbm/chen2/raw_data/big_data/separated/Q0011_mRFU057_G02.feather")

In [ ]:
df

,v_gene,j_gene,cdr3_nt,cdr3,templates,sample_name
0,TRBV2,TRBJ1-5,TGTGCCACCGGGGGGGGTAGCAATCAGCCCCAGCATTTT,CATGGGSNQPQHF,31,Q0011_mRFU057_G02
1,TRBV6-5,TRBJ1-5,TGTGCCAGCAGTTACGGCGGTAGCAATCAGCCCCAGCATTTT,CASSYGGSNQPQHF,62,Q0011_mRFU057_G02
2,TRBV5-6,TRBJ1-5,TGTGCCAGCAGCCTGCGGCGACGTAGCAATCAGCCCCAGCATTTT,CASSLRRRSNQPQHF,112,Q0011_mRFU057_G02
3,TRBV15,TRBJ1-5,TGTGCCACCAGCAGAGATTGGGGTAGCAATCAGCCCCAGCATTTT,CATSRDWGSNQPQHF,25,Q0011_mRFU057_G02
4,TRBV30,TRBJ1-5,TGTGCCTGGAGTATGGGCAGTAGCAATCAGCCCCAGCATTTT,CAWSMGSSNQPQHF,2,Q0011_mRFU057_G02

In [4]:
df_prepared = pd.read_feather("/dsi/sbm/chen2/raw_data/big_data/prepared_df.ftr")

In [6]:
df_prepared.head()

,v_gene,j_gene,cdr3_nt,cdr3,templates,sample_name,cdr3_truncated
0,TRBV4-1,TRBJ1-5,TGCGCCAGCAGCCAAGGAGGAGTTAGCAATCAGCCCCAGCATTTT,CASSQGGVSNQPQHF,15,S0108_mRFU2_D01,QGGVSNQP
1,TRBV2,TRBJ1-5,TGTGCCAGCAGTCCGGACAGGGATAGCAATCAGCCCCAGCATTTT,CASSPDRDSNQPQHF,32,S0108_mRFU2_D01,PDRDSNQP
2,TRBV6-1,TRBJ1-5,TGTGCCAGCAGTGATCGGGCAGGGAATAGCAATCAGCCCCAGCATTTT,CASSDRAGNSNQPQHF,32,S0108_mRFU2_D01,DRAGNSNQ
3,TRBV6-1,TRBJ1-5,TGTGCCAGCAGTAGCGGGACTCTTAGCAATCAGCCCCAGCATTTT,CASSSGTLSNQPQHF,72,S0108_mRFU2_D01,SGTLSNQP
4,TRBV6-2,TRBJ1-5,TGTGCCAGCAGAACCGACGGGTCTAGCAATCAGCCCCAGCATTTT,CASRTDGSSNQPQHF,28,S0108_mRFU2_D01,TDGSSNQP

In [7]:
metadata = pd.read_csv("/dsi/sbm/chen2/raw_data/big_data/metadata.tsv", delimiter="\t")

In [12]:
metadata.head()

,sample_name,is_cancer,age_years,Gender,race_parsed,stage_parsed,productive_templates,productive_rearrangements,smoking,has_benign_nodule,has_copd,has_heart_disease,median_umi_count,total_umi_M,Histology,VJ_lot
0,S0394_mRFU073_G01,False,66,Female,Caucasian,NaN,"5,691,937","302,611",Former smoker,NaN,NaN,NaN,11,5.061063,NaN,A
1,S0280_mRFU076_H02,False,54,Female,Caucasian,NaN,"5,026,104","183,134",Non-smoker,True,NaN,NaN,9,4.409110,NaN,A
2,S0225_mRFU073_F03,False,57,Male,Caucasian,NaN,"4,752,047","204,511",Current smoker,NaN,NaN,NaN,11,4.098710,NaN,A
3,S0643_mRFU075_F01,False,56,Female,Caucasian,NaN,"4,627,253","276,229",Current smoker,NaN,NaN,NaN,9,4.126059,NaN,A
4,S0264_mRFU075_C01,False,56,Female,Caucasian,NaN,"4,618,812","115,095",Former smoker,True,NaN,NaN,13,4.348374,NaN,A